vendored-plugins/openproject-backlogs/config/routes.rb
#-- copyright
# OpenProject Backlogs Plugin
#
# Copyright (C)2013-2014 the OpenProject Foundation (OPF)
# Copyright (C)2011 Stephan Eckardt, Tim Felgentreff, Marnen Laibow-Koser, Sandro Munda
# Copyright (C)2010-2011 friflaj
# Copyright (C)2010 Maxime Guilbot, Andrew Vit, Joakim Kolsjö, ibussieres, Daniel Passos, Jason Vasquez, jpic, Emiliano Heyns
# Copyright (C)2009-2010 Mark Maglana
# Copyright (C)2009 Joe Heck, Nate Lowrie
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3.
#
# OpenProject Backlogs is a derivative work based on ChiliProject Backlogs.
# The copyright follows:
# Copyright (C) 2010-2011 - Emiliano Heyns, Mark Maglana, friflaj
# Copyright (C) 2011 - Jens Ulferts, Gregor Schmidt - Finn GmbH - Berlin, Germany
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

OpenProject::Application.routes.draw do
  scope '', as: 'backlogs' do
    scope 'projects/:project_id', as: 'project' do
      resources :backlogs,         controller: :rb_master_backlogs,  only: :index

      resources :sprints,          controller: :rb_sprints,          only: :update do
        resource :query,            controller: :rb_queries,          only: :show

        resource :taskboard,        controller: :rb_taskboards,       only: :show

        resource :wiki,             controller: :rb_wikis,            only: [:show, :edit]

        resource :burndown_chart,   controller: :rb_burndown_charts,  only: :show

        resources :impediments,      controller: :rb_impediments,      only: [:create, :update]

        resources :tasks,            controller: :rb_tasks,            only: [:create, :update]

        resources :export_card_configurations, controller: :rb_export_card_configurations, only: [:index, :show] do
          resources :stories,          controller: :rb_stories,          only: [:index]
        end

        resources :stories,          controller: :rb_stories,          only: [:create, :update]
      end
    end
  end

  get 'projects/:project_id/versions/:id/edit' => 'version_settings#edit'
  post 'projects/:id/project_done_statuses' => 'projects#project_done_statuses'
  post 'projects/:id/rebuild_positions' => 'projects#rebuild_positions'
end

vendored-plugins/openproject-backlogs/app/views/projects/settings/_backlogs_settings.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% statuses_done_for_project = @project.done_statuses.select(:id).map(&:id) %>

<%= styled_form_tag(controller: '/projects', action: "project_done_statuses", id: @project) do %>

<fieldset class="form--fieldset" id="form--backlogs">
  <legend class="form--fieldset-legend"><%=l('backlogs.definition_of_done')%></legend>
  <div class="form--fieldset-control">
    <span class="form--fieldset-control-container">
      (<%= check_all_links 'form--backlogs' %>)
    </span>
  </div>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table" id="material_budget_items">
        <colgroup>
          <col highlight-col>
          <col highlight-col>
        </colgroup>
        <thead>
          <tr>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Status.model_name.human %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%=l('backlogs.work_package_is_closed')%>
                  </span>
                </div>
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
          <% for status in (@statuses || []) %>
            <tr>
              <td>
                <%= status.name %>
              </td>
              <td style="text-align:left">
                <% checkbox_id = status.name.parameterize.underscore %>
                <%= styled_label_tag checkbox_id, l('backlogs.label_is_done_status', status_name: status.name), class: 'hidden-for-sighted' %>
                <%= (styled_check_box_tag 'statuses[][status_id]', status.id.to_s, statuses_done_for_project.include?(status.id), id: checkbox_id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="generic-table--action-buttons">
    <%= styled_button_tag l(:button_save), class: '-highlight -with-icon icon-checkmark' %>
  </div>
</fieldset>

<% end %>

<h3><%=l('backlogs.rebuild_positions')%></h3>

<%= styled_form_tag(:controller => '/projects', :action => "rebuild_positions", :id => @project) do %>
  <p><%= styled_button_tag l('backlogs.rebuild'), class: '-highlight' %></p>
<% end %>

vendored-plugins/openproject-backlogs/app/views/projects/settings/_versions.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<% if @project.shared_versions.any? %>
  <fieldset class="form--fieldset">
    <legend class="form--fieldset-legend">
      <%= l(:label_available_project_versions) %>
    </legend>
    <div class="generic-table--container">
      <div class="generic-table--results-container">
        <table class="generic-table">
          <colgroup>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col>
          </colgroup>
          <thead>
            <tr>
              <th>
                <div class="generic-table--sort-header-outer">
                  <div class="generic-table--sort-header">
                    <span>
                      <%= Version.model_name.human %>
                    </span>
                  </div>
                </div>
              </th>
              <th>
                <div class="generic-table--sort-header-outer">
                  <div class="generic-table--sort-header">
                    <span>
                      <%= Version.human_attribute_name(:start_date) %>
                    </span>
                  </div>
                </div>
              </th>
              <th>
                <div class="generic-table--sort-header-outer">
                  <div class="generic-table--sort-header">
                    <span>
                      <%= Version.human_attribute_name(:effective_date) %>
                    </span>
                  </div>
                </div>
              </th>
              <th>
                <div class="generic-table--sort-header-outer">
                  <div class="generic-table--sort-header">
                    <span>
                      <%= Version.human_attribute_name(:description) %>
                    </span>
                  </div>
                </div>
              </th>
              <th>
                <div class="generic-table--sort-header-outer">
                  <div class="generic-table--sort-header">
                    <span>
                      <%= Version.human_attribute_name(:status) %>
                    </span>
                  </div>
                </div>
              </th>
              <th>
                <div class="generic-table--sort-header-outer">
                  <div class="generic-table--sort-header">
                    <span>
                      <%= Version.human_attribute_name(:sharing) %>
                    </span>
                  </div>
                </div>
              </th>
              <th>
                <div class="generic-table--sort-header-outer">
                  <div class="generic-table--sort-header">
                    <span>
                      <%= WikiPage.model_name.human %>
                    </span>
                  </div>
                </div>
              </th>
              <th><div class="generic-table--empty-header"></div></th>
            </tr>
          </thead>
          <tbody>
            <% for version in @project.shared_versions.sort %>
              <tr class="version <%= 'shared' if version.project != @project %>">
                <td class="name <%=h version.status %><% ' icon-context icon-link' if version.project != @project %>">
                  <%= link_to_version version %>
                </td>
                <td class="date"><%= format_date(version.start_date) %></td>
                <td class="date"><%= format_date(version.effective_date) %></td>
                <td class="description"><%=h version.description %></td>
                <td class="status"><%= l("version_status_#{version.status}") %></td>
                <td class="sharing"><%=h format_version_sharing(version.sharing) %></td>
                <td>
                  <%= link_to_if_authorized( h(version.wiki_page_title),
                                             { controller: '/wiki',
                                               action: 'show',
                                               project_id: version.project,
                                               id: version.wiki_page_title }) ||
                      h(version.wiki_page_title) unless version.wiki_page_title.blank? || version.project.wiki.nil? %>
                </td>
                <td class="buttons">
                  <% if version.project == @project %>
                    <%= link_to_if_authorized l(:button_edit),
                                              { controller: '/versions', action: 'edit', id: version },
                                              class: 'icon icon-edit' %>
                    <%= link_to_if_authorized l(:button_delete),
                                              { controller: '/versions', action: 'destroy', id: version },
                                              data: { confirm: l(:text_are_you_sure) },
                                              method: :delete,
                                              class: 'icon icon-delete' %>
                  <% elsif @project.enabled_modules.collect(&:name).include?("backlogs") %>
                    <%= link_to_if_authorized l(:button_edit),
                                              { :controller => '/versions', :action => 'edit', :id => version, :project_id => @project.id },
                                              :class => 'icon icon-edit' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="generic-table--action-buttons">
      <%= link_to_if_authorized({ controller: '/versions', action: 'new', project_id: @project },
                            { class: 'button -alt-highlight',
                              aria: {label: t(:label_version_new)},
                              title: t(:label_version_new)}) do %>
        <%= op_icon('button--icon icon-add') %>
        <span class="button--text"><%= l(:label_version) %></span>
      <% end %>
    </div>
  <% else %>
    <%= no_results_box(action_url: new_project_version_path(@project), display_action: authorize_for('versions', 'new')) %>
  <% end %>
</fieldset>

<% if @project.versions.any? %>
  <div class="contextual">
      <%= link_to l(:label_close_versions),
                  close_completed_project_versions_path(@project),
                  method: :put %>
  </div>
<% end %>